# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manejocampos.ui'
#
# Created: Tue Apr 17 10:02:22 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(600, 576)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Administrador de Correo", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 50, 571, 461))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tableWidget = QtGui.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 551, 351))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("MainWindow", "Id", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("MainWindow", "New Column", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("MainWindow", "Fecha", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("MainWindow", "Estado", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.frame = QtGui.QFrame(self.tab_2)
        self.frame.setGeometry(QtCore.QRect(70, 330, 431, 91))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.BtnBorrar = QtGui.QPushButton(self.frame)
        self.BtnBorrar.setGeometry(QtCore.QRect(270, 50, 97, 27))
        self.BtnBorrar.setText(QtGui.QApplication.translate("MainWindow", "Borrar", None, QtGui.QApplication.UnicodeUTF8))
        self.BtnBorrar.setObjectName(_fromUtf8("BtnBorrar"))
        self.BtnAdicionar = QtGui.QPushButton(self.frame)
        self.BtnAdicionar.setGeometry(QtCore.QRect(70, 50, 97, 27))
        self.BtnAdicionar.setText(QtGui.QApplication.translate("MainWindow", "Adicionar", None, QtGui.QApplication.UnicodeUTF8))
        self.BtnAdicionar.setObjectName(_fromUtf8("BtnAdicionar"))
        self.BtnModificar = QtGui.QPushButton(self.frame)
        self.BtnModificar.setGeometry(QtCore.QRect(170, 50, 97, 27))
        self.BtnModificar.setText(QtGui.QApplication.translate("MainWindow", "Modificar", None, QtGui.QApplication.UnicodeUTF8))
        self.BtnModificar.setObjectName(_fromUtf8("BtnModificar"))
        self.BtnAnterior = QtGui.QPushButton(self.frame)
        self.BtnAnterior.setGeometry(QtCore.QRect(90, 10, 31, 21))
        self.BtnAnterior.setText(QtGui.QApplication.translate("MainWindow", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.BtnAnterior.setObjectName(_fromUtf8("BtnAnterior"))
        self.BtnProximo = QtGui.QPushButton(self.frame)
        self.BtnProximo.setGeometry(QtCore.QRect(280, 10, 31, 21))
        self.BtnProximo.setText(QtGui.QApplication.translate("MainWindow", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.BtnProximo.setObjectName(_fromUtf8("BtnProximo"))
        self.LblRegistro = QtGui.QLabel(self.frame)
        self.LblRegistro.setGeometry(QtCore.QRect(120, 10, 161, 21))
        self.LblRegistro.setFrameShape(QtGui.QFrame.Panel)
        self.LblRegistro.setFrameShadow(QtGui.QFrame.Sunken)
        self.LblRegistro.setText(QtGui.QApplication.translate("MainWindow", "0/0", None, QtGui.QApplication.UnicodeUTF8))
        self.LblRegistro.setAlignment(QtCore.Qt.AlignCenter)
        self.LblRegistro.setObjectName(_fromUtf8("LblRegistro"))
        self.BtnFinal = QtGui.QPushButton(self.frame)
        self.BtnFinal.setGeometry(QtCore.QRect(310, 10, 31, 21))
        self.BtnFinal.setText(QtGui.QApplication.translate("MainWindow", ">|", None, QtGui.QApplication.UnicodeUTF8))
        self.BtnFinal.setObjectName(_fromUtf8("BtnFinal"))
        self.BtnPrincipio = QtGui.QPushButton(self.frame)
        self.BtnPrincipio.setGeometry(QtCore.QRect(60, 10, 31, 21))
        self.BtnPrincipio.setText(QtGui.QApplication.translate("MainWindow", "|<", None, QtGui.QApplication.UnicodeUTF8))
        self.BtnPrincipio.setObjectName(_fromUtf8("BtnPrincipio"))
        self.frame_2 = QtGui.QFrame(self.tab_2)
        self.frame_2.setGeometry(QtCore.QRect(10, 0, 521, 321))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.label_15 = QtGui.QLabel(self.frame_2)
        self.label_15.setGeometry(QtCore.QRect(10, 40, 111, 31))
        self.label_15.setFrameShape(QtGui.QFrame.Box)
        self.label_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_15.setMidLineWidth(0)
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "TSL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_9 = QtGui.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(10, 170, 111, 31))
        self.label_9.setFrameShape(QtGui.QFrame.Box)
        self.label_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_9.setMidLineWidth(0)
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Bandera", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_8 = QtGui.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 111, 31))
        self.label_8.setFrameShape(QtGui.QFrame.Box)
        self.label_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_8.setMidLineWidth(0)
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Servidor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_12 = QtGui.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(380, 10, 61, 31))
        self.label_12.setFrameShape(QtGui.QFrame.Box)
        self.label_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_12.setMidLineWidth(0)
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Puerto", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.frame_2)
        self.label_13.setGeometry(QtCore.QRect(10, 140, 111, 31))
        self.label_13.setFrameShape(QtGui.QFrame.Box)
        self.label_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_13.setMidLineWidth(0)
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Enviado Por", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.frame_2)
        self.label_14.setGeometry(QtCore.QRect(10, 110, 111, 31))
        self.label_14.setFrameShape(QtGui.QFrame.Box)
        self.label_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_14.setMidLineWidth(0)
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Clave", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_11 = QtGui.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(10, 200, 111, 31))
        self.label_11.setFrameShape(QtGui.QFrame.Box)
        self.label_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_11.setMidLineWidth(0)
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Ruta salida PDF", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_10 = QtGui.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(10, 80, 111, 31))
        self.label_10.setFrameShape(QtGui.QFrame.Box)
        self.label_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_10.setMidLineWidth(0)
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Usuario", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.CmbTls = QtGui.QComboBox(self.frame_2)
        self.CmbTls.setGeometry(QtCore.QRect(120, 40, 85, 27))
        self.CmbTls.setObjectName(_fromUtf8("CmbTls"))
        self.CmbTls.addItem(_fromUtf8(""))
        self.CmbTls.setItemText(0, QtGui.QApplication.translate("MainWindow", "Si", None, QtGui.QApplication.UnicodeUTF8))
        self.CmbTls.addItem(_fromUtf8(""))
        self.CmbTls.setItemText(1, QtGui.QApplication.translate("MainWindow", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.TxtPuerto = QtGui.QPlainTextEdit(self.frame_2)
        self.TxtPuerto.setGeometry(QtCore.QRect(440, 10, 61, 31))
        self.TxtPuerto.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.TxtPuerto.setTabChangesFocus(True)
        self.TxtPuerto.setPlainText(QtGui.QApplication.translate("MainWindow", "25", None, QtGui.QApplication.UnicodeUTF8))
        self.TxtPuerto.setObjectName(_fromUtf8("TxtPuerto"))
        self.TxtHost = QtGui.QPlainTextEdit(self.frame_2)
        self.TxtHost.setGeometry(QtCore.QRect(120, 10, 251, 31))
        self.TxtHost.setTabChangesFocus(True)
        self.TxtHost.setPlainText(QtGui.QApplication.translate("MainWindow", "localhost", None, QtGui.QApplication.UnicodeUTF8))
        self.TxtHost.setObjectName(_fromUtf8("TxtHost"))
        self.TxtUsuario = QtGui.QPlainTextEdit(self.frame_2)
        self.TxtUsuario.setGeometry(QtCore.QRect(120, 80, 381, 31))
        self.TxtUsuario.setTabChangesFocus(True)
        self.TxtUsuario.setPlainText(_fromUtf8(""))
        self.TxtUsuario.setObjectName(_fromUtf8("TxtUsuario"))
        self.TxtClave = QtGui.QPlainTextEdit(self.frame_2)
        self.TxtClave.setGeometry(QtCore.QRect(120, 110, 381, 31))
        self.TxtClave.setTabChangesFocus(True)
        self.TxtClave.setPlainText(_fromUtf8(""))
        self.TxtClave.setObjectName(_fromUtf8("TxtClave"))
        self.TxtEnviado = QtGui.QPlainTextEdit(self.frame_2)
        self.TxtEnviado.setGeometry(QtCore.QRect(120, 140, 381, 31))
        self.TxtEnviado.setTabChangesFocus(True)
        self.TxtEnviado.setPlainText(_fromUtf8(""))
        self.TxtEnviado.setObjectName(_fromUtf8("TxtEnviado"))
        self.TxtBandera = QtGui.QPlainTextEdit(self.frame_2)
        self.TxtBandera.setGeometry(QtCore.QRect(120, 170, 381, 31))
        self.TxtBandera.setTabChangesFocus(True)
        self.TxtBandera.setPlainText(_fromUtf8(""))
        self.TxtBandera.setObjectName(_fromUtf8("TxtBandera"))
        self.TxtRuta = QtGui.QPlainTextEdit(self.frame_2)
        self.TxtRuta.setGeometry(QtCore.QRect(120, 200, 381, 31))
        self.TxtRuta.setTabChangesFocus(True)
        self.TxtRuta.setPlainText(_fromUtf8(""))
        self.TxtRuta.setObjectName(_fromUtf8("TxtRuta"))
        self.label_16 = QtGui.QLabel(self.frame_2)
        self.label_16.setGeometry(QtCore.QRect(10, 260, 111, 31))
        self.label_16.setFrameShape(QtGui.QFrame.Box)
        self.label_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_16.setMidLineWidth(0)
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Contenido txt", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.TxtCuerpoTexto = QtGui.QPlainTextEdit(self.frame_2)
        self.TxtCuerpoTexto.setGeometry(QtCore.QRect(120, 260, 381, 31))
        self.TxtCuerpoTexto.setTabChangesFocus(True)
        self.TxtCuerpoTexto.setPlainText(_fromUtf8(""))
        self.TxtCuerpoTexto.setObjectName(_fromUtf8("TxtCuerpoTexto"))
        self.label_17 = QtGui.QLabel(self.frame_2)
        self.label_17.setGeometry(QtCore.QRect(10, 290, 111, 31))
        self.label_17.setFrameShape(QtGui.QFrame.Box)
        self.label_17.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_17.setMidLineWidth(0)
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Contenido html", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.TxtCuerpo_html = QtGui.QPlainTextEdit(self.frame_2)
        self.TxtCuerpo_html.setGeometry(QtCore.QRect(120, 290, 381, 31))
        self.TxtCuerpo_html.setTabChangesFocus(True)
        self.TxtCuerpo_html.setPlainText(_fromUtf8(""))
        self.TxtCuerpo_html.setObjectName(_fromUtf8("TxtCuerpo_html"))
        self.label_18 = QtGui.QLabel(self.frame_2)
        self.label_18.setGeometry(QtCore.QRect(10, 230, 111, 31))
        self.label_18.setFrameShape(QtGui.QFrame.Box)
        self.label_18.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_18.setMidLineWidth(0)
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Ruta PDF Add.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.TxtRuta_2 = QtGui.QPlainTextEdit(self.frame_2)
        self.TxtRuta_2.setGeometry(QtCore.QRect(120, 230, 381, 31))
        self.TxtRuta_2.setTabChangesFocus(True)
        self.TxtRuta_2.setPlainText(_fromUtf8(""))
        self.TxtRuta_2.setObjectName(_fromUtf8("TxtRuta_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuArchivo = QtGui.QMenu(self.menubar)
        self.menuArchivo.setTitle(QtGui.QApplication.translate("MainWindow", "Archivo", None, QtGui.QApplication.UnicodeUTF8))
        self.menuArchivo.setObjectName(_fromUtf8("menuArchivo"))
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        self.actionSalir = QtGui.QAction(MainWindow)
        self.actionSalir.setText(QtGui.QApplication.translate("MainWindow", "Salir", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSalir.setObjectName(_fromUtf8("actionSalir"))
        self.menuArchivo.addAction(self.actionSalir)
        self.menubar.addAction(self.menuArchivo.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.CmbTls.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.TxtHost)
        MainWindow.setTabOrder(self.TxtHost, self.TxtPuerto)
        MainWindow.setTabOrder(self.TxtPuerto, self.CmbTls)
        MainWindow.setTabOrder(self.CmbTls, self.TxtUsuario)
        MainWindow.setTabOrder(self.TxtUsuario, self.TxtClave)
        MainWindow.setTabOrder(self.TxtClave, self.TxtEnviado)
        MainWindow.setTabOrder(self.TxtEnviado, self.TxtBandera)
        MainWindow.setTabOrder(self.TxtBandera, self.TxtRuta)
        MainWindow.setTabOrder(self.TxtRuta, self.TxtRuta_2)
        MainWindow.setTabOrder(self.TxtRuta_2, self.TxtCuerpoTexto)
        MainWindow.setTabOrder(self.TxtCuerpoTexto, self.TxtCuerpo_html)
        MainWindow.setTabOrder(self.TxtCuerpo_html, self.BtnPrincipio)
        MainWindow.setTabOrder(self.BtnPrincipio, self.BtnAnterior)
        MainWindow.setTabOrder(self.BtnAnterior, self.BtnProximo)
        MainWindow.setTabOrder(self.BtnProximo, self.BtnFinal)
        MainWindow.setTabOrder(self.BtnFinal, self.BtnAdicionar)
        MainWindow.setTabOrder(self.BtnAdicionar, self.BtnModificar)
        MainWindow.setTabOrder(self.BtnModificar, self.BtnBorrar)
        MainWindow.setTabOrder(self.BtnBorrar, self.tableWidget)

    def retranslateUi(self, MainWindow):
        item = self.tableWidget.horizontalHeaderItem(0)
        item = self.tableWidget.horizontalHeaderItem(1)
        item = self.tableWidget.horizontalHeaderItem(2)
        item = self.tableWidget.horizontalHeaderItem(3)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Estado", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Configuración", None, QtGui.QApplication.UnicodeUTF8))

